
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallbacks to the current hardcoded values
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://xxx.supabase.co";
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "xxx";


export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
