
name: Playwright Tests

on:
  pull_request:
    branches:
      - prod

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
        
      - name: Start Supabase project
        run: |
          # Initialize the Supabase project (if not already initialized)
          supabase init --force --with-intellij-settings --with-vscode-settings 

          # Start the Supabase services (Postgres, Auth, Storage)
          supabase start


      - name: Set up database schema
        run: |
          export SUPABASE_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres

          # Drop schema and reset the database (assuming schema.sql exists in 'data/schema.sql')
          # psql $SUPABASE_URL -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
          # psql $SUPABASE_URL -f data/schema.sql

          # Run migrations (if applicable)
          #supabase migrations up

          # insert first user
          psql $SUPABASE_URL -f tests/data/auth.users.sql 
          psql $SUPABASE_URL -f tests/data/auth.identities.sql 
          psql $SUPABASE_URL -f tests/data/profiles.sql 


      - name: Create .env file
        run: |
          echo "# Supabase Configuration" > .env
          echo "VITE_SUPABASE_URL=http://127.0.0.1:54321" >> .env
          echo "VITE_SUPABASE_ANON_KEY=$(supabase status 2>/dev/null | grep 'anon key' | awk '{print $3}')" >> .env


      - name: Install Playwright
        run: npm install @playwright/test  
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
